### ISSUE TITLE
First push todo list

### ISSUE THREAD

**Issue by hbinkim** [hbinkim/hbinkim.github.io#1]
- [ ] complete about page
- [ ] dark mode <-> light mode transition check
- [ ] disque 연동
- [ ] google analytics 연동
- [ ] complete the first post
