### ISSUE TITLE
Post todo list

### ISSUE THREAD

**Issue by hbinkim** [hbinkim/hbinkim.github.io#2]
- [ ] crd
  - [ ] condition array vs status
  - [ ] capacity vs resource
- [ ] install k8s cluster with kubespray on specific os
- [ ] migrate gitlab pipeline to github pipeline
